# Generated by Django 4.2 on 2025-06-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_ipn_callback_url_payment_nowpayments_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_wallet',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('confirming', 'Confirming Payment'), ('confirmed', 'Confirmed'), ('sending', 'Sending to Merchant'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='waiting', max_length=20),
        ),
    ]
