# Generated by Django 4.2 on 2025-06-28 01:45

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_payment_wallet_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEF', length=10, max_length=10, prefix='', primary_key=True, serialize=False),
        ),
    ]
