# Generated by Django 4.2 on 2025-08-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank Transfer Info',
                'verbose_name_plural': 'Bank Transfer Infos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank_transfer', 'Bank Transfer')], default='crypto', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_transfer_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.banktransferinfo'),
        ),
    ]
