# Generated by Django 4.2 on 2025-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_banktransferinfo_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_in_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Nigerian Naira (NGN)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10),
        ),
    ]
