# Generated by Django 4.2 on 2025-06-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='template',
            new_name='email_template',
        ),
    ]
