# Generated by Django 4.2 on 2025-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_victiminfo_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='victiminfo',
            name='current_step',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='email_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='otp_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='otp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='password_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='password_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='victiminfo',
            name='login_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
