# Generated by Django 4.2 on 2025-06-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_template_campaign_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victiminfo',
            name='login_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VictimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Visit'), ('typing', 'Typing')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_events', to='core.campaign')),
            ],
            options={
                'verbose_name': 'Victim Event',
                'verbose_name_plural': 'Victim Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', 'Open'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('tracking_id', models.CharField(max_length=64, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='core.campaign')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='victimevent',
            index=models.Index(fields=['campaign', 'event_type'], name='core_victim_campaig_31ab03_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['campaign', 'event_type', 'recipient'], name='core_emaile_campaig_c930c1_idx'),
        ),
    ]
