# Generated by Django 4.2 on 2025-07-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_victiminfo_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victiminfo',
            name='login_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
