# Generated by Django 4.2 on 2025-07-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_victiminfo_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victiminfo',
            name='login_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
